spring:
  application:
    name: assignment-service
  datasource:
    url: jdbc:mysql://localhost:3306/workdb
    username: root
    password: Tech@2021*
    
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8083
#Eureka
eureka:
 client:
  service-url:
   defaultZone: http://localhost:8761/eureka/  
#task-service:
#  ribbon:
#    listOfServers: http://localhost:8083/,http://localhost:8085/
application:
  version: assignment-service-v1
